name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-14-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select Xcode version
        uses: actions/setup-xcode@v2  # Use the latest version, e.g., v2 or higher
        with:
          xcode-version: '16.0' # Match this to your project format 77 requirement

      - name: Build and Test
        run: |
          xcodebuild -scheme TestGitActions -destination 'platform=iOS Simulator,name=iPhone 14' clean build test
